<?php

namespace AppBundle\Repository;

/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends AbstractRepository
{
    public function search($term, $order = 'asc', $limit = 20, $offset = 0)
    {
        $qb = $this
            ->createQueryBuilder('u')
            ->select('u')
            ->orderBy('u.id', $order)
        ;

        if ($term) {
            $qb
                ->where('u.id',$term)
            ;
        }

        return $this->paginate($qb, $limit, $offset);
    }
}
